### ISSUE TITLE
Do not have user privileges required to open \\.\COMx

### ISSUE THREAD

**Issue by Jir8taiwan** [joric/arduino-bitcoin-miner#11]
Hi, Whom may concern,

I am trying your code to access my small ESP32 board to know what different is than other builder.
I have a problem to connect the device in win10, although I have successfully upload the compiled program.
My command line is as following:
`\\bfgminer-5.4.2-win64\mn.exe -o stratum+tcp://address:port -u wallet.esp32 -p x -S bfl@\\.\COM3`

It is responding a fail message in the miner that cannot open the device of port (mine is COM3).
**Do not have user privileges required to open \\.\COM3**

However, if I use serial monitor, it can get response when I enter.
```
23:23:59.703 -> ESP-ROM:esp32s3-20210327
23:23:59.703 -> Build:Mar 27 2021
23:23:59.703 -> rst:0x8 (TG1WDT_SYS_RST),boot:0xb (SPI_FAST_FLASH_BOOT)
23:23:59.703 -> Saved PC:0x420068c7
23:23:59.703 -> SPIWP:0xee
23:23:59.703 -> mode:DIO, clock div:1
23:23:59.703 -> load:0x3fce3808,len:0x44c
23:23:59.703 -> load:0x403c9700,len:0xbe4
23:23:59.703 -> load:0x403cc700,len:0x2a38
23:23:59.751 -> entry 0x403c98d4
```

I am not sure any wrong step, but could I have tip from your help?
Thank you very much.

**Comment by joric** [comment]
Sorry, I don't have ESP32.
