### ISSUE TITLE
Are STRATUM mining not supported?

### ISSUE THREAD

**Issue by microboard** [joric/arduino-bitcoin-miner#3]
If it's a version issue, I'll check it out. Are STRATUM mining not supported? I am using BFG 5.2.

**Comment by joric** [comment]
Stratum is handled by BFG, check BFG settings. Hardware miner only knows Icarus and doesn't do networking.

**Comment by microboard** [comment]
So, is there any accurate process data for the Icarus protocol? I need a spec. And I want to meet you if you come to Korea.

**Comment by joric** [comment]
It's not well documented, but there's a few notes in the project readme. Also thanks, but I did't plan to visit Korea just yet.

**Comment by microboard** [comment]
Ok.  Can you send me an Icarus spec? If you come to Korea I will welcome you.  And can you send me the version you are using? I still have communication error problems.

**Comment by joric** [comment]
I don't have Icarus specs. Everything I know about Icarus is here https://github.com/joric/arduino-bitcoin-miner/blob/master/README.md

**Comment by josephchrzempiec** [comment]
I know this is a strange question to ask. but ma i ask what hash rate are you hashing at?
