### ISSUE TITLE
BITCOIN POOL CONNECTION

### ISSUE THREAD

**Issue by gggabriella** [joric/arduino-bitcoin-miner#5]
Have anyone connected this program directly to the pool through a wifi connection in the microcontroller? If you have any leads regarding direct pool connections please help.

I'm trying to connect to this specific pool:
https://slushpool.com/help/manual/stratum-protocol#download

With the Lolin v3 ESP8622 microcontroller

**Comment by reVox96** [comment]
This may be pretty tricky to accomplish, and i think ESP alone would have better hashrate than Arduino alone (but idk how much ram it has) - check https://www.instructables.com/id/ESP8266-Bitcoin-Miner/ for more info, but i think it also needs to be connected to PC. You would need to write something to connect to pool.

**Comment by gggabriella** [comment]
I'm aware of it's total inefficiency, I just need to make it happen for a critical mining art project. In fact I'm looking fwd to find the slowest hash rate and measure slowest mining in PR vs NL, in 2 art expos simultaneously.  

That ESP miner instructable doesn't lead anywhere, the few instructions that exists all need to be connected to computers, I know that it's possible to connect directly through wifi with that ESP module to the above (stratum-protocol) slushpool, here's another ref:
https://github.com/muimota/miniminer

My main problem is all I know is javascript, and arduino based compiling with these modules... If someone can make me a program that can connect the module to the blockchain directly through wifi... I'm willing to pay

**Comment by josephchrzempiec** [comment]
Hello does anyone know If it's still possible to make this miner to work like Joric did in his video?

**Comment by joric** [comment]
@josephchrzempiec yes.
