### ISSUE TITLE
ICA 0: Comms error (werr=1)          

### ISSUE THREAD

**Issue by 000212** [joric/arduino-bitcoin-miner#8]
Looks like bytes are recived (in Arduino Leonardo) but bfgminer got this error.

Command:
bfgminer -o pool -u user -p pass -S ica:\\.\COM3 --icarus-options 115200:1:1

**Comment by ErikV7-official** [comment]
Found the issue but not the solution, the issue it is the for in the case. The sentence it takes a long time to break.

```
for (uint32_t nonce=0; 1 ; nonce++) 
{
  if (!midstate_hashing(hash, (uint8_t*)buf, nonce))
  {
    reply(nonce);
    break;
  }
  if (nonce==0xffffffff)
  {
    break;
  }
}
```
