### ISSUE TITLE
Litecoin Scrypt on Intel Galileo Gen 1

### ISSUE THREAD

**Issue by fcapuano** [joric/arduino-bitcoin-miner#9]
I have this board that It has some useful Memory. Can you easly implement Scrypt?
I can give a try

**Comment by joric** [comment]
I doubt it's possible with 2.5k ram.

**Comment by fcapuano** [comment]
Ok. Wikipedia says 256MB. Maybe is wrong reporter. Thx

https://en.m.wikipedia.org/wiki/Intel_Galileo

**Comment by joric** [comment]
Oh you meant Intel Galileo. I only code for Pro Micro.

**Comment by fcapuano** [comment]
Only FYI Intel Galileo is Arduino certified and code compatibile. Your Bitcoin code run likes a charm on Galileo.
